### ISSUE TITLE
DOCTYPE syntax

### ISSUE THREAD

**Issue by zakuro9715** [b-html/b-html#34]
b-html don't have doctype syntax now and use text syntax like `><!DOCTYPE html>`

 Because html4.01 doctype is so complex and all html doctype is long (I don't want to type `shift-d-o-c-t-y-p-e` 8 keys), I propose new syntax for doctype like `<! html-versoin`.

`html-version` is simple text for generate complex doctype.

| b-html doctype | html doctype |
| --- | --- |
| `<!html` | `DOCTYPE html` |
| `<!html4 strict` | `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">` |
| `<!html4 transiitional` | `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">` |
| `<!html4 frameset` | `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">` |

It's a just idea. So I would like to get many feedbacks.

**Comment by bouzuya** [comment]
NOTE: 
- jade: http://jade-lang.com/reference/doctype/
- haml: http://haml.info/docs/yardoc/file.REFERENCE.html#doctype_
- slim: http://www.rubydoc.info/gems/slim/frames#IE_conditional_comment_______

**Comment by zakuro9715** [comment]
I refered to slim(https://github.com/slim-template/slim#doctype-tag) before create this issue

**Comment by zakuro9715** [comment]
Oh! `<!` already had assigned the comment syntax. So we can't use it for doctype.

**Comment by bouzuya** [comment]
I think it may be breaking changes. `<!html` would not have been rarely used.

**Comment by zakuro9715** [comment]
What do you think to assign `<!` as a doctype and assign `<-` as a comment?

**Comment by bouzuya** [comment]
I think that
- `<!doctype ...` -> `<!DOCTYPE ...>` ... doctype
- `<!-- ...` -> `<!-- ... -->` ... HTML comment 
- `<!` -> (remove) ... b-html comment

Problem:
- `<!` is not always to be b-html comment. I want to another syntax.

NOTE:

I do not want to use the `<!` prefix for the doctype syntax only. Becase `<!` prefix is used for both DOCTYPE (`<!DOCTYPE`) and COMMENT (`<!--`) in HTML. I want to use `<!` prefix for the HTML comment.

**Comment by zakuro9715** [comment]
Hmm..

I agree to HTML comment and doctype.

And as you say, `<!` should not be assigned to b-html comment.
I think that b-html comment does't have to start with `<` like `<!`, <-`.

What do you think that b-html comment assigned to `//` like some another languages?

**Comment by bouzuya** [comment]
- `<!doctype ...` -> `<!DOCTYPE ...>` ... doctype
- `<!-- ...` -> `<!-- ... -->` ... HTML comment
- `<-` -> (remove) ... b-html comment

**Comment by bouzuya** [comment]
@zakuro9715 See: #42

**Comment by bouzuya** [comment]
I added HTML5 shorthand in #42.
I will add another shorthands in #45
