### ISSUE TITLE
can't compile when line has tail spaces

### ISSUE THREAD

**Issue by zakuro9715** [b-html/b-html#37]
``` js
var bHtml = require('b-html')
bHtml('<html') // => '<html></html>'
bHtml('<html ') // => '<html '
```

**Comment by bouzuya** [comment]
Do you want to throw an error ?

**Comment by zakuro9715** [comment]
hmm... I want to throw an error or output `<html></html>`(equal to `bHtml('<html')`)

I think that if tail extra spaces doesn't allowed, it throw an error or if tail extra specs allowed, it ignore tail extra spaces.

In any case, It should enyone can understand compile result

**Comment by bouzuya** [comment]
I think so, too.

**Comment by bouzuya** [comment]
@zakuro9715 See: #47
